spring:
  opentelemetry:
    traces:
      exporter:
        otlp:
          endpoint: http://localhost:4317
      sampler:
        probability: 1.0
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://localhost:4317
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true