global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['localhost:8888']

  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:9092']  # Добавьте свои метрики Kafka здесь при необходимости
