spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sabexzero/shuttle-microservices
          search-paths:
            - configuration
            - configuration/general
server:
  port: 8000
